services:
  btapi:
    container_name: telegram-bot-api-docker
    image: ram3a9670/telegram-bot-api-docker:latest
    restart: always
    volumes:
      - .:/app
    command: >
      bash -c "cd telegram-bot-api/bin && ./telegram-bot-api --api-id ${API_ID} --api-hash ${API_HASH} -p ${PORT} --local -v 1"
    networks:
      - default
    env_file:
      - .env

networks:
  default:
    name: surentm
    external: true
