name: Telegram Bot Api Docker CI/CD

on:
  push:
    branches: [ "main" ]

jobs:

  build_and_push:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        logout: false

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platform: linux/amd64
        push: true
        tags: ${{ secrets.REGISTERY }}/telegram-bot-api-docker:latest
        provenance: false


  deploy:

    needs: build_and_push
    runs-on: ubuntu-latest

    steps:

    - name: SSH to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_PRIVATE_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          cd /root/telegram-bot-api-docker
          ls -la
          git pull origin main
          docker compose pull
          docker compose up -d
